// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ-Lexx88AnTygXsKV5hdkjSmLoN741bg',
    appId: '1:624608240138:web:e3552687bcd9ae339935f3',
    messagingSenderId: '624608240138',
    projectId: 'loadup-app-decee',
    authDomain: 'loadup-app-decee.firebaseapp.com',
    storageBucket: 'loadup-app-decee.firebasestorage.app',
    measurementId: 'G-7HJSBMDD4Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7cxT7eLlR4uqjmD9y6AsUSlyfpNWc0DE',
    appId: '1:624608240138:android:f1fd9692bb0c1c6e9935f3',
    messagingSenderId: '624608240138',
    projectId: 'loadup-app-decee',
    storageBucket: 'loadup-app-decee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUaksQdOgYc5rJg0r_FlRf4EofpL2ILpM',
    appId: '1:624608240138:ios:d003288b797e748b9935f3',
    messagingSenderId: '624608240138',
    projectId: 'loadup-app-decee',
    storageBucket: 'loadup-app-decee.firebasestorage.app',
    iosBundleId: 'com.example.loadup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUaksQdOgYc5rJg0r_FlRf4EofpL2ILpM',
    appId: '1:624608240138:ios:d003288b797e748b9935f3',
    messagingSenderId: '624608240138',
    projectId: 'loadup-app-decee',
    storageBucket: 'loadup-app-decee.firebasestorage.app',
    iosBundleId: 'com.example.loadup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZ-Lexx88AnTygXsKV5hdkjSmLoN741bg',
    appId: '1:624608240138:web:3ca9f4a417e019c09935f3',
    messagingSenderId: '624608240138',
    projectId: 'loadup-app-decee',
    authDomain: 'loadup-app-decee.firebaseapp.com',
    storageBucket: 'loadup-app-decee.firebasestorage.app',
    measurementId: 'G-3THNS7W1JG',
  );

}